apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: my-react-app:latest
          ports:
            - containerPort: 5000
