# SERVER
server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://dbcontainer:3306/db_todo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: todo-service

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          globally_qouted_identifiers: true

